{
  "hash": "57bfca65ee086f8133327297788f19bc",
  "result": {
    "markdown": "---\ntitle: \"Confidence Intervall\"\nauthor: \"Johannes Buck\"\ndate: \"2023-07-30\"\ncategories: [statistics, risk management]\ndescription: A confidence interval is a statistical interval that contains the location of a true parameter of a population with a certain probability.\nimage: teaser_image.png\n---\n\n\nA confidence interval is a statistical concept used to provide an estimate for an unknown parameter in a population. It indicates how certain or trustworthy that estimate is. Confidence intervals are often used in the context of hypothesis testing and estimation in statistics.\n\nIn statistics, a confidence interval is usually defined as a range of values within which the true value of a parameter lies with a certain probability. For example, a 95% confidence interval indicates that there is a 95% probability that the true value of the parameter lies within that interval.\n\nThe calculation of a confidence interval depends on the underlying statistical model and the distribution of the data. Typically, the standard normal distribution or the t-distribution is used, depending on the size of the sample.\n\nConfidence intervals are useful to account for uncertainty in estimates and to better interpret the results of studies or surveys.\n\n## Parameter estimation\n\nThere are two estimation methods in inferential statistics:\n\n-   point estimation\n\n-   interval estimation\n\n### Point estimation\n\nIn point estimation, properties about the population are determined as exact values and are usually given a measure of the estimation error.\n\n### Interval estimation\n\nIn interval estimation, an interval is specified for the characteristic of the population, and this is then given a confidence interval (e.g., 95%).\n\n### Conclusion\n\nPoint estimation pretends \"pseudo-accuracy\". The estimated parameter value is given with point accuracy, although the true parameter value is very rarely hit exactly.\n\n![](/posts/confidence%20interval/intervall%20vs%20point%20estimation.png)\n\nYou can compare a point estimate to trying to hit a fly (the true parameter value) with a pin (point estimate). With a fly swatter (interval), the probability of hitting the fly is much higher.\n\n## Confidence Interval Definition\n\nA confidence interval is a statistical interval that contains the location of a true parameter of a population with a certain probability. A confidence level of 95% contains the true value with 95% probability. However, a confidence level of 95% does not mean that 95% of the data lies within this interval.\n\n![](/posts/confidence%20interval/Konfidenzintervall.png)\n\nThe intervals $\\hat{\\theta}_A$, $\\hat{\\theta}_B$ and $\\hat{\\theta}_E$ do not contain the true value $\\theta$.\n\nThe intervals $\\hat{\\theta}_A$ and $\\hat{\\theta}_E$ belong to the 5% of the \"least likely\" (farthest from the true value) sample values.\n\nA confidence interval has a lower bound $x_u$ and an upper bound $x_o$.\n\n$\\bar{x}$ denotes the mean of the data set, $z_u$ and $z_o$ are the z-transformed interval limits.\n\nThe standard error is the fraction of the standard deviation $s_x$ and the square root of the sample size $n$.\n\n$$ \\begin{equation} \\tag{1.0}\n    \\large x_u = \\bar{x} + z_u \\cdot \\frac{s_x}{\\sqrt{n}}\n\\end{equation} $$\n\n$$ \\begin{equation} \\tag{1.1}\n    \\large x_o = \\bar{x} + z_o \\cdot \\frac{s_x}{\\sqrt{n}}\n\\end{equation} $$\n\n## Example\n\nCalculate the 95% confidence interval for the monthly snack spending of a group of people.\n\n**Step 1: Calculate the estimated parameter**\n\nCalculate the mean $\\bar{x}$ from the existing data set.\n\n| \\# participants | Monthly snack spending USD |\n|-----------------|----------------------------|\n| 20              | 8                          |\n| 30              | 32                         |\n| 10              | 0                          |\n| 30              | 48                         |\n| 10              | 16                         |\n\nSample size $\\large n = 20+30+10+30+10 = 100$\n\n$\\large \\bar{x}=\\frac{20\\cdot8+30\\cdot32+10\\cdot0+30\\cdot48+10\\cdot16}{100}= \\text{USD } 27.2$\n\n**Step 2: Transform the interval limits into standard normally distributed values**\n\nWith a confidence level of 95%, we obtain the following interval limits: the lower limit is 2.5% $= x_u = 0.025$ and the upper limit is 97.5% $x_o = 0.975$.\n\nWe now need to standardize these values by looking at the z-distribution table.\n\n-   For the upper bound $x_o$, the z-value is easy to read: $x_o = 0.975$ corresponds to $z_o = 1.960$.\n\n-   Since the normal distribution is symmetric and mirrored on the x-axis, the lower limit $z_u = -1.960$ results in\n\n![](/posts/confidence%20interval/z-Verteilungstabelle.png)\n\nWith a mean of $\\bar{x} = 27.20$ USD, a lower limit of $z_u= -1.960$, an upper limit of $z_o= 1.960$ and a sample size of $n = 100$, all required parameters for the formula are given except for the standard deviation $s_x$.\n\n**Step 3: Calculation of variance and standard deviation**\n\nThe variance can be calculated using the values from the table as follows:\n\n$\\large s_x^2=\\ \\frac{\\left(8-27.2\\right)^2\\cdot20+\\left(32-27.2\\right)^2\\cdot30+\\left(0-27.2\\right)^2\\cdot10+\\left(48-27.2\\right)^2\\cdot30+\\left(16-27.2\\right)^2\\cdot10}{100}$\n\n$\\large s_x^2=296.96$\n\nThe standard deviation is the square root of the variance:\n\n$\\large s_x=\\sqrt{s_x^2}=\\sqrt{296.96}=17.23$\n\n**Step 4: Calculation of lower and upper limit**\n\n$\\large x_u=\\ \\bar{x}+\\ z_u\\ \\cdot\\ \\frac{s_x}{\\sqrt n}=27.2+\\left(-1.960\\right)\\cdot\\frac{17.23}{\\sqrt{100}}=23.82$\n\n$\\large x_o=\\ \\bar{x}+\\ z_o\\ \\cdot\\ \\frac{s_x}{\\sqrt n}=27.2+1.960\\cdot\\frac{17.23}{\\sqrt{100}}=30.58$\n\nThus, the limits of the contingency interval are at points 23.82 and 30.58. The conclusion is: with 95% confidence, the true mean for the group of people's monthly snack spending is between USD 23.82 and USDF 30.58.\n\n## Z-Distribution\n\nBy performing a z-standardization, we can transform the normal distribution into a standard normal distribution. This can be done with any normal distribution (but only with normal distributions). This gives us a distribution that is always the same, with mean $µ = 0$ and standard deviation $σ = 1$. Just like the normal distribution, the standard normal distribution tells you what percentage of values fall within a given range. Now, this range no longer depends on $µ$ and $σ$, but is standardized.\n\n![](/posts/confidence%20interval/Normal%20Distribution.png)\n\n![](/posts/confidence%20interval/Standard%20Normal%20Distribution.png)\n\nIn the standard normal distribution, approximately 68.2% of the values always lie in the range between $z = -1$ and $z = +1$. Or put another way: There is a 68.2% probability that the value is between -1 and +1.\n\nUsing a z-transformation or z-standardization, you subtract the arithmetic mean from each measured value, divide the resulting difference by the standard deviation, and you get the so-called *z-scores*.\n\nAs formula (with $x$ for the respective value, $μ$ for the arithmetic mean and $σ$ for the standard deviation) $$z=\\frac{x-μ}σ$$\n\nAfter the z-transformation\n\n-   the arithmetic mean of the transformed series is always zero, and\n\n-   the variance and standard deviation are always 1.\n\nIf a normal distribution is present, the corresponding probabilities can be read from a standard normal distribution table based on the z-values. The standard normal table contains only positive z-values. Since the normal distribution is symmetric and mirrored on the x-axis, the z-value for the lower limit results from the negative z-value for the upper limit $z_u = -z_o$.\n\n## Three Sigma Rule\n\nThe \"Three Sigma Rule\" is a statistical rule used to quantify the probability of events within a normally distributed data set.\n\n![](/posts/confidence%20interval/Drei-Sigma-Regel.png)\n\nThe three sigma rule states that\\\na) 68.3% of the data are within one standard deviation of the mean ($\\mu \\pm \\sigma$).\n\nb\\) 95.4% of the data are within two standard deviations of the mean ($\\mu \\pm 2\\sigma$).\n\nc\\) 99.7% of the data are within 3 standard deviations of the mean ($\\mu \\pm 3\\sigma$).\n\n::: callout-note\nThe three-sigma rule applies only to normally distributed data sets. The three sigma rule does not apply to skewed triangular distributions.\n:::\n\n## R code\n\n**Example 1 -- Confidence interval of dataset**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate confidence interval with function t.test from core package stats\n\n# Sample data\ndata <- c(23, 28, 32, 27, 25, 30, 31, 29, 26, 24)\n\n# Calculate the confidence interval\n# The function t.test performs the Student's t-Tests on vectors of data\n# By default conf.level=0.95\nresult <- t.test(data)\n\n# Extract the confidence interval\nconfidence_interval <- result$conf.int\n\n# Get the lower bound and the upper bound of the confidence interval\nlower_bound <- result$conf.int[1]\nupper_bound <- result$conf.int[2]\n\n# Print lower bound and uppder bound of the confidence interval\ncat(\"Lower bound of the 95% confidence interval:\", lower_bound, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLower bound of the 95% confidence interval: 25.33415 \n```\n:::\n\n```{.r .cell-code}\ncat(\"Upper bound of the 95% confidence interval:\", upper_bound, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nUpper bound of the 95% confidence interval: 29.66585 \n```\n:::\n\n```{.r .cell-code}\n# Plot histogram\nplot(data, main = \"Histogram\", xlab = \"Data\", ylab = \"Value\")\n\n# Draw lower bound and upper bound of the confidence interval\nabline(h = lower_bound, col = 'red', lwd = 1, lty = 2)\ntext(x = 1.5, y = lower_bound+0.3, labels = \"lower bound\", col = \"#4D4D4D\")\nabline(h = upper_bound, col = 'red', lwd = 1, lty = 2)\ntext(x = 1.5, y = upper_bound+0.3, labels = \"upper bound\", col = \"#4D4D4D\")\n```\n\n::: {.cell-output-display}\n![](confidence-interval_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nThe 95% confidence interval is `[25.3, 29.7]`.\n\n**Example 2 -- Univariate Statistic (Median)**\n\nFor this example, we will generate $n = 100$ observations from a standard normal distribution, and use the median as the parameter/statistic of interest. Note that the true (population) median is zero. Since the median is a univariate statistic, the bootstrap distribution will be a vector of length $R + 1$ containing the bootstrap replicates of the median.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Univariate Statistic (Median)\n\nlibrary(nptest)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nPackage 'nptest' version 1.1\nType 'citation(\"nptest\")' to cite this package.\n```\n:::\n\n```{.r .cell-code}\n# generate 100 standard normal observations\nset.seed(1)\nn <- 100\nx <- rnorm(n)\n\n# nonparametric bootstrap\nnpbs <- np.boot(x = x, statistic = median)\nnpbs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nNonparametric Bootstrap of Univariate Statistic\nusing R = 9999 bootstrap replicates\n\n  t0: 0.1139\n  SE: 0.1394\nBias: 0.0185 \n\nBCa Confidence Intervals:\n      lower  upper\n90% -0.0566 0.3411\n95% -0.0811 0.3673\n99% -0.1351 0.3940\n```\n:::\n\n```{.r .cell-code}\n# check t0, SE, and bias\nmedian(x)                          # t0\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1139092\n```\n:::\n\n```{.r .cell-code}\nsd(npbs$boot.dist)                 # SE\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1393567\n```\n:::\n\n```{.r .cell-code}\nmean(npbs$boot.dist) - npbs$t0     # Bias\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01845341\n```\n:::\n\n```{.r .cell-code}\n# bootstrap distribution\nhist(npbs$boot.dist,\n     xlab = \"t*\",\n     ylab = \"Density\",\n     main = \"Bootstrap Distribution\")\n\n# Observed median\nabline(v = npbs$t0,\n       lty = 2,\n       col = \"red\")\n\n# CI 95% lower boundary\nabline(v = npbs$bca[2, 1],\n       lty = 2,\n       col = \"blue\")\n\n# CI 95% upper boundary\nabline(v = npbs$bca[2, 2],\n       lty = 2,\n       col = \"blue\")\n\nlegend(\n  \"topleft\",\n  legend = c(\"t0\", \"CI 95%\"),\n  col = c(\"red\", \"blue\"),\n  lty = 2,\n  bty = \"n\"\n)\n```\n\n::: {.cell-output-display}\n![](confidence-interval_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n### \n",
    "supporting": [
      "confidence-interval_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}